Update sqlite3 so it builds on recent node.
xiph/awcy pull request #351
Opened 2023-05-03 06:03 UTC by tdaede

This also updates the package-lock.json and version.

2023-05-03 23:45 UTC, vibhoothi requested changes
Uh-huh, 

This is giving me build-time failures when trying on top of #349 [as that would be the case so i tested like that, yet to try standalone]

Debug trace
<Details>

```log

 ---> f4cc42053396
Step 30/38 : RUN 	cd ${APP_DIR} && 	export PYTHON=python2.7 && 	alias python=python2.7 && 	rm -rf node_modules && 	npm install && 	npm run tsc
 ---> Running in 295c0a2263ae
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @types/form-data@2.5.0: This is a stub types definition. form-data provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

> iconv@2.2.3 install /opt/app/node_modules/iconv
> node-gyp rebuild

make: Entering directory '/opt/app/node_modules/iconv/build'
  CXX(target) Release/obj.target/iconv/src/binding.o
../src/binding.cc:35:11: error: ‘v8::Handle’ has not been declared
   35 | using v8::Handle;
      |           ^~~~~~
../src/binding.cc:65:26: error: ‘Handle’ has not been declared
   65 |   static void Initialize(Handle<Object> obj)
      |                          ^~~~~~
../src/binding.cc:65:32: error: expected ‘,’ or ‘...’ before ‘<’ token
   65 |   static void Initialize(Handle<Object> obj)
      |                                ^
../src/binding.cc: In static member function ‘static void {anonymous}::Iconv::Initialize(int)’:
../src/binding.cc:70:5: error: ‘obj’ was not declared in this scope
   70 |     obj->Set(Nan::New<String>("make").ToLocalChecked(),
      |     ^~~
../src/binding.cc:71:60: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   71 |              Nan::New<FunctionTemplate>(Make)->GetFunction());
      |                                                            ^
In file included from /root/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:60,
                 from ../src/binding.cc:18:
/root/.cache/node-gyp/12.16.1/include/node/v8.h:6126:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6126 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/root/.cache/node-gyp/12.16.1/include/node/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
../src/binding.cc:73:63: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   73 |              Nan::New<FunctionTemplate>(Convert)->GetFunction());
      |                                                               ^
In file included from /root/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:60,
                 from ../src/binding.cc:18:
/root/.cache/node-gyp/12.16.1/include/node/v8.h:6126:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6126 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/root/.cache/node-gyp/12.16.1/include/node/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided
../src/binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Iconv::Make(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:84:44: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’
   84 |     String::Utf8Value from_encoding(info[0]);
      |                                            ^
In file included from /root/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:60,
                 from ../src/binding.cc:18:
/root/.cache/node-gyp/12.16.1/include/node/v8.h:3135:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
 3135 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
      |     ^~~~~~~~~
/root/.cache/node-gyp/12.16.1/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
../src/binding.cc:85:42: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’
   85 |     String::Utf8Value to_encoding(info[1]);
      |                                          ^
In file included from /root/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:60,
                 from ../src/binding.cc:18:
/root/.cache/node-gyp/12.16.1/include/node/v8.h:3135:5: note: candidate: ‘v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)’
 3135 |     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
      |     ^~~~~~~~~
/root/.cache/node-gyp/12.16.1/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
../src/binding.cc:92:64: error: no matching function for call to ‘v8::ObjectTemplate::NewInstance()’
   92 |         Nan::New<ObjectTemplate>(object_template)->NewInstance();
      |                                                                ^
In file included from /root/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:60,
                 from ../src/binding.cc:18:
/root/.cache/node-gyp/12.16.1/include/node/v8.h:6423:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::ObjectTemplate::NewInstance(v8::Local<v8::Context>)’
 6423 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(Local<Context> context);
      |                                            ^~~~~~~~~~~
/root/.cache/node-gyp/12.16.1/include/node/v8.h:6423:44: note:   candidate expects 1 argument, 0 provided
../src/binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Iconv::Convert(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:103:49: error: no matching function for call to ‘v8::Value::BooleanValue()’
  103 |     const bool is_flush = info[8]->BooleanValue();
      |                                                 ^
In file included from /root/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:60,
                 from ../src/binding.cc:18:
/root/.cache/node-gyp/12.16.1/include/node/v8.h:2699:8: note: candidate: ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
 2699 |   bool BooleanValue(Isolate* isolate) const;
      |        ^~~~~~~~~~~~
/root/.cache/node-gyp/12.16.1/include/node/v8.h:2699:8: note:   candidate expects 1 argument, 0 provided
In file included from /root/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14,
                 from /root/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /root/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:60,
                 from ../src/binding.cc:18:
/root/.cache/node-gyp/12.16.1/include/node/v8.h:2702:51: note: candidate: ‘v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const’
 2702 |                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
      |                                                   ^~~~~~~~~~~~
/root/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/root/.cache/node-gyp/12.16.1/include/node/v8.h:2702:51: note:   candidate expects 1 argument, 0 provided
 2702 |                 V8_WARN_UNUSED_RESUL [...]

2023-05-03 23:51 UTC, tdaede commented
can you try again after running "npm install"

2023-05-03 23:53 UTC, vibhoothi commented
@tdaede : This is running via Docker Build without Cache, with the upstream Dockerfile
https://github.com/xiph/awcy/blob/master/Dockerfile

The only thing I am suspecting now is the Node version. What is there,

2023-05-04 13:11 UTC, vibhoothi approved these changes
Now it works,
Amazing, thanks.

2023-05-04 13:14 UTC, vibhoothi commented
Packages deprecations warnings on build

For the main server
```bash
> cd ${APP_DIR} && 	export PYTHON=python2.7 && 	alias python=python2.7 && 	rm -rf node_modules && 	npm install && 	npm run tsc
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @types/form-data@2.5.0: This is a stub types definition. form-data provides its own type definitions, so you do not need this installed.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
```


For www/*
```bash
> cd ${APP_DIR}/www && 	npm install && 	npm run build
npm WARN deprecated @types/immutable@3.8.7: This is a stub types definition for Facebook's Immutable (https://github.com/facebook/immutable-js). Facebook's Immutable provides its own type definitions, so you don't need @types/immutable installed!
npm WARN deprecated core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```


Webpack build warnings
```bash
> webpack --mode=development --config config/webpack.config.js

(node:40) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'reduce' is deprecated)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:40) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
```

2023-05-12 20:12 UTC, merged